#!/usr/bin/env fish

#
# ~/.fishrc
#

oh-my-posh init fish --config ~/.poshthemes/rudolfs-light.omp.json | source
neofetch --size 300
set     fish_greeting
set     fish_color_command white
set -gx EDITOR vim
set -gx VISUAL vim
set -gx BROWSER /usr/bin/firefox
set -U SXHKD_SHELL sh

alias ls "lsd"
alias ll "lsd -l"
alias la "lsd -A"

alias gcl      "git clone"
alias neofetch "neofetch --size 300"

function fish_title
    set -q argv[1]; or set argv fish
    echo (fish_prompt_pwd_dir_length=1 prompt_pwd): $argv;
end

sh -c "$(export FZF_DEFAULT_OPTS=' --height 13')"

# chips
if [ -e ~/.config/chips/build.fish ] ; . ~/.config/chips/build.fish ; end
