#! /bin/sh

~/.config/polybar/launch.sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI

bspc config border_width         0
bspc config window_gap           4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
##bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a mpv state=floating
bspc rule -a spotify desktop='^4'
bspc rule -a firefox desktop='^3'
bspc rule -a Pavucontrol state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a feh state=floating
